services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    command: uvicorn backend:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:6
    ports:
      - "6379:6379"
