# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"\xa7\x01\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\x0c\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0c\n\x04side\x18\x04 \x01(\x05\x12\x1c\n\x14\x61verage_traded_price\x18\x05 \x01(\x02\x12\x17\n\x0ftraded_quantity\x18\x06 \x01(\x05\x12\x13\n\x0border_alive\x18\x07 \x01(\x08\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"9\n\x08OrderPSI\x12\x10\n\x08order_id\x18\x01 \x01(\x0c\x12\x0c\n\x04side\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=16
  _globals['_ORDER']._serialized_end=183
  _globals['_ORDERPSI']._serialized_start=185
  _globals['_ORDERPSI']._serialized_end=242
# @@protoc_insertion_point(module_scope)
